project_name: octoforward
release:
  github:
    owner: 2phost
    name: octoforward
builds:
  - id: octoforward
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/2phost/octoforward/pkg/version.version=
archives:
  - id: octoforward
    builds:
    - octoforward
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
