apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: octoforward
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/2phost/octoforward/releases/download/v0.1.0/octoforward_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./octoforward"
      to: "."
    - from: LICENSE
      to: "."
    bin: "octoforward"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/2phost/octoforward/releases/download/v0.1.0/octoforward_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./octoforward"
      to: "."
    - from: LICENSE
      to: "."
    bin: "octoforward"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/2phost/octoforward/releases/download/v0.1.0/octoforward_windows_amd64.zip
    sha256: ""
    files:
    - from: "/octoforward.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "octoforward.exe"
  shortDescription: A new plugin
  homepage: https://github.com/2phost/octoforward
  caveats: |
    Usage:
      $ kubectl octoforward

    For additional options:
      $ kubectl octoforward --help
      or https://github.com/2phost/octoforward/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
